language: node_js
node_js: stable
dist: trusty
sudo: required
addons:
  firefox: latest
  sauce_connect: true
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install -g bower polylint web-component-tester
- bower install
- bower install paper-input
- polylint
script:
- xvfb-run wct
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct -s 'default'; fi
env:
  global:
  - secure: 146TBWIvSoGC4ti2x5rkalB9gM7OGPvx+dqCv0p/ypSwqpusTZpjJO8jlLqrZk+w1PSvm56Rh6wZ+c2N1N+xuWoPxWqy8FQlqM42zpS+dj11rszhyumT+uXQU4ywSU8ac4mvh/evRTWP0KvvB6a+6536vSRBWQsunxfH21jZUYLF3aHZHV7Lid4GxiehKY2Chv7s2Agww+j2QTBPIdnWR+xVTnNJ7jWkPG91VumgwQ/eU6+/ZF35nEl6ISiJdAUxKGYSAofXhmQ6H8Fbplz74zOUWE+BjU+exiQdLrp/6+eCazz27QG5thGy0NKHJpfmSKN+L3cfhrVbNM9KxHHCaL+YubhzBXtfYEtmzBK1JQmNI7nppYpL2eM0dTPbHHauso2a8tnG0jE2m6Iuo0LYyHWjOCJoLvd86x+/e5tKLA5cQAAG7scBTpQfN0DGwEDmB+U/P1gebYb9rQSaJ60F4hetkutZZQdhzS1M6Dr8nz+W/1ftBd0HFElvMBQx55MwwSg7s0e3bWrhzRNSXVUsDNm8XuqeFe5rquM8+3HIvxIXcvc31SOuIWCzzx5T6hwoXHC7fx5X0hOzyiM1cwTrgKuRt+4777qCjoQ9coqu6CEspY6aUXHw1s3Up3p6lHbJw9C5sQ5aWIykUNE6/EHHVUBWB8wyEDSx9ocvkKQSVqw=
  - secure: y2ZKeGbpQEFGzlDqsrlbAeWmfeK/oPT+5XlXOuepmsAYxgDl0V8ozFzKf6QpSqi9SQEnzum9InuT3mCruuH01epD18X25z121AsxFmckcAGKSoEZ/FZvL9sSwkNrzaIDcd5aPekxf44cw934WkmT0bc6JjQzWEhWygpapBKWtqwbgF0TIFPDyfr7mKfQxHm0HHaOsZ+lKdJnyDC9idJyjfzXGqpv69F+ZaXgCUY0AvCHNHXPCaWXoXqHy6UDuX8vqdkTv85ixFxjk/NKpH43H+obmHrCYNql37WhI1amsTSiilEqEj6E0zHeqSEYs0JAUI5/e/vqx2IUPN6wXK3OhhpRArBw31rJU2uf8hg92x3xj7r1xmXVg+RgzyL3qAiNgQdZZmndYQp6+CI+US9XlDPYjujI5E7sRoqhV/jHu+MS682Ti1RP/kyebAnWOawKUz8LISnj/IAyhqKzjkfY7e/VPNcaJT5iymG+y2HlUMk+9jBQ2zfwvm+8uTg4NwzF8/hAJfcV98ZV+depmAa2UG9w9CYeWbt6AlgB9XtxfqO9ICWSAJ3+1V6MFT51kYTddvBmBMDcF0DTTZZUroO4Tfzw79FeP2rdz1Ci1S3uBLOdaw9oW2E3RyGe5mAUxAJCo5HI61poo/93K221IFele94cTLuPLfNHA8Jawn1W/s0=
